// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://euolfwwsaoslcnuowvrl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV1b2xmd3dzYW9zbGNudW93dnJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyNzAzOTksImV4cCI6MjA1NTg0NjM5OX0.GUtQz7P0UDde0QxOetJooc_wt9Fv57R7Cka27R1sEkA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);